# Generated by Django 3.1.3 on 2021-06-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('created_at',)},
        ),
    ]
